name: 'medical_project'
version: '1.0.0'
config-version: 2

profile: 'medical_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_project:
    bronze:
      +materialized: table
      +schema: bronze
      +tags: ["bronze", "raw"]
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver", "cleaned"]
    gold:
      +materialized: table
      +schema: gold
      +tags: ["gold", "analytics"]

snapshots:
  medical_project:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

seeds:
  medical_project:
    +schema: reference
    +quote_columns: false

vars:
  source_database: "MEDICAL_DB"
  source_schema: "RAW"
  senior_age_threshold: 65
  high_amount_threshold: 1000
